# Application configuration
spring.application.name=${SPRING_APP_NAME:security-middleware}
server.port=${SPRING_APP_PORT:7070}

# JWT configuration
jwt.secret=${JWT_SECRET:kED95zhQY/++v+/dYr99UoL2oIWVCOccRxTBCk+tTPE=}
jwt.issuer=${JWT_ISSUER:entelgy.com}

# JWT expiration
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION:604800000}
jwt.temporalExpiration=${JWT_TEMPORAL_expiration:30000}

# JWT expiration for testing (1 min and 5 min)
#jwt.expiration=${JWT_EXPIRATION:60000}
#jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION:300000}