# Application configuration
spring.application.name=${SPRING_APP_NAME:security-middleware}
server.port=${SPRING_APP_PORT:7070}

# JWT configuration
jwt.secret=${JWT_SECRET:kED95zhQY/++v+/dYr99UoL2oIWVCOccRxTBCk+tTPE=}
jwt.issuer=${JWT_ISSUER:entelgy.com}

# JWT expiration

# Tiempo de vida del token de sesión: 20 minutos
jwt.sessionExpiration=${JWT_SESSION_EXPIRATION:1200000}

# Tiempo de vida del token de acceso: 5 minutos
jwt.accessExpiration=${JWT_ACCESS_EXPIRATION:300000}

# Tiempo de vida del token de refresco: 20 minutos (opcional, si lo usas por tiempo)
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION:1200000}

# Máximo número de usos del token de refresco
jwt.maxRefresh=${JWT_MAX_REFRESH:3}

# Tiempo de vida del token temporal (Sessiontmp): 30 segundos
jwt.temporalExpiration=${JWT_TEMPORAL_expiration:30000}